#!/bin/bash

echo "🤖 Bull Bot Setup Summary"
echo "========================="
echo ""
echo "✅ Configuration Complete:"
echo "   - API keys configured in flaskServer/config.py"
echo "   - Environment files created for client and server"
echo "   - All dependencies installed"
echo "   - Server URLs configured for local development"
echo ""
echo "⚠️  ACTION REQUIRED:"
echo ""
echo "1. 📊 SET UP PINECONE INDEX"
echo "   - Go to https://app.pinecone.io/"
echo "   - Log in with your Pinecone account"
echo "   - Click 'Create Index'"
echo "   - Index name: bullbot"
echo "   - Dimensions: 384"
echo "   - Metric: cosine"
echo "   - Cloud: AWS"
echo "   - Region: us-east-1"
echo ""
echo "2. 💳 FIX OPENAI API QUOTA"
echo "   - Your OpenAI API key has exceeded its quota"
echo "   - Go to https://platform.openai.com/account/billing"
echo "   - Add payment method and credits"
echo "   - Or use a different API key with available quota"
echo ""
echo "3. 📤 UPLOAD DATA TO PINECONE (After step 1 & 2)"
echo "   Run: python upload_to_pinecone.py"
echo ""
echo "4. 🚀 START THE APPLICATION"
echo "   You'll need 3 terminal windows:"
echo ""
echo "   Terminal 1 - Flask Server:"
echo "   cd flaskServer && python app.py"
echo ""
echo "   Terminal 2 - Express Server:"
echo "   cd server && npm start"
echo ""
echo "   Terminal 3 - Vite Client:"
echo "   cd client && npm run dev"
echo ""
echo "5. 🌐 ACCESS THE APP"
echo "   Open your browser to: http://localhost:5173"
echo ""
echo "========================="
echo "📝 Quick Start Commands"
echo "========================="
echo ""
echo "# After completing steps 1 & 2 above, run these in order:"
echo ""
echo "# 1. Upload data to Pinecone:"
echo "python upload_to_pinecone.py"
echo ""
echo "# 2. Start all servers (in 3 separate terminals):"
echo "cd flaskServer && python app.py"
echo "cd server && npm start"
echo "cd client && npm run dev"
echo ""
